/**
 * 地点 town 与「隶属于主景点」belongsToSpot 映射。
 * belongsToSpot 仅用于「位于某主景点内部」的子点位，不用于城镇归属（如 Hobart 城内 POI）。
 */

/** 子景点 enTitle → 所属主景点标识（与主卡片 enTitle 一致） */
export const SPOT_PARENT_BY_EN_TITLE = {
  'Adventure Bay': 'Bruny Island',
  'Mavista Nature Walk': 'Bruny Island',
  'Two Tree Point': 'Bruny Island',
  'Eaglehawk Neck': 'Tasman Peninsula',
  'Tessellated pavement': 'Tasman Peninsula',
  'Cape Pillar': 'Tasman Peninsula',
  'Cape Hauy': 'Tasman Peninsula',
  'Roaring Beach': 'Tasman Peninsula',
  'Spiky Bridge': 'Tasman Peninsula',
  'Spiky Beach': 'Tasman Peninsula',
  'Norfolk Bay': 'Tasman Peninsula',
  'Frederick Henry Bay': 'Tasman Peninsula',
  'The Painted Cliff': 'Maria Island',
  'Maria Island National Park': 'Maria Island',
  'Darlington Probation Station': 'Maria Island',
  'Dove Lake': 'Cradle Mountain',
  'Barn Bluff': 'Cradle Mountain',
  'Walls of Jerusalem National Park': 'Cradle Mountain',
  'Devils Gullet State Reserve': 'Cradle Mountain',
  'Wineglass Bay': 'Freycinet National Park',
  'Honeymoon Bay': 'Freycinet National Park',
  'Great Oyster Bay': 'Freycinet National Park',
  'Moulting Lagoon': 'Freycinet National Park',
  'Ocean Beach': 'Strahan',
  'Gordon River': 'Strahan',
  'Macquarie Harbour': 'Strahan',
  'Southwest National Park': 'Strahan',
  'Franklin-Gordon Wild Rivers National Park': 'Strahan',
  'West Coast Wilderness Railway': 'Strahan',
  'Philosopher Falls': 'Strahan',
  'King Solomons Cave': 'Mole Creek',
  'Marakoopa Cave': 'Mole Creek',
  'Mole Creek Caves': 'Mole Creek',
  'Mole Creek Karst National Park': 'Mole Creek',
  'Strzelecki National Park': 'Flinders Island',
  'Strzelecki Peaks': 'Flinders Island',
  'Deal Island': 'Flinders Island',
  'Killiecrankie': 'Flinders Island',
  'Russell Falls': 'Mount Field National Park',
  'Horseshoe Falls': 'Mount Field National Park',
  'Lady Barron Falls': 'Mount Field National Park',
  'Mount Mawson': 'Mount Field National Park',
}

/** 子景点中文 title → 所属主景点标识 */
export const SPOT_PARENT_BY_TITLE = {
  '冒险湾': 'Bruny Island',
  '马维斯塔自然步道': 'Bruny Island',
  '两棵树角步道': 'Bruny Island',
  '鹰颈峡': 'Tasman Peninsula',
  '棋盘道': 'Tasman Peninsula',
  '皮勒角': 'Tasman Peninsula',
  '豪伊角': 'Tasman Peninsula',
  '咆哮海滩': 'Tasman Peninsula',
  'Spiky Bridge': 'Tasman Peninsula',
  'Spiky Beach': 'Tasman Peninsula',
  '诺福克湾': 'Tasman Peninsula',
  '弗雷德里克亨利湾': 'Tasman Peninsula',
  '彩绘崖': 'Maria Island',
  '鸽子湖': 'Cradle Mountain',
  '谷仓崖': 'Cradle Mountain',
  '酒杯湾': 'Freycinet National Park',
  '蜜月湾': 'Freycinet National Park',
  '大牡蛎湾': 'Freycinet National Park',
  '莫尔廷泻湖': 'Freycinet National Park',
  '海洋海滩': 'Strahan',
  '戈登河': 'Strahan',
  '麦夸里港': 'Strahan',
  '西南国家公园': 'Strahan',
  '富兰克林戈登野河国家公园': 'Strahan',
  '西海岸荒野铁路': 'Strahan',
  '罗素瀑布': 'Mount Field National Park',
  '马蹄瀑布': 'Mount Field National Park',
  '巴伦夫人瀑布': 'Mount Field National Park',
  '莫森山': 'Mount Field National Park',
}

/** 主景点标识 → 列表分组用的 town（地点+邮编） */
export const SPOT_PARENT_TOWN_MAP = {
  'Bruny Island': 'Bruny Island',
  'Tasman Peninsula': 'Tasman Peninsula',
  'Maria Island': 'Triabunna',
  'Cradle Mountain': 'Cradle Mountain',
  'Freycinet National Park': 'Coles Bay',
  'Coles Bay': 'Coles Bay',
  'Strahan': 'Strahan',
  'Mole Creek': 'Mole Creek',
  'Flinders Island': 'Flinders Island',
  'Mount Field National Park': 'Hobart',
}

/** 主景点标识 → 卡片「隶属于」展示用中文名 */
export const SPOT_PARENT_DISPLAY_NAMES = {
  'Bruny Island': '布鲁尼岛',
  'Tasman Peninsula': '塔斯曼半岛',
  'Maria Island': '玛丽亚岛',
  'Cradle Mountain': '摇篮山',
  'Freycinet National Park': '菲欣纳国家公园',
  'Coles Bay': '科尔斯湾',
  'Strahan': '斯特拉恩',
  'Mole Creek': '摩尔溪',
  'Flinders Island': '弗林德斯岛',
  'Mount Field National Park': '费尔德山国家公园',
}

/** 主景区 enTitle 别名（belongsToSpot 标识 → 可能的主卡片 enTitle） */
export const SPOT_PARENT_EN_TITLE_ALIASES = {
  'Tasman Peninsula': ['Turrakana/Tasman Peninsula'],
  'Freycinet National Park': ['Coles Bay'],
  'Mount Field National Park': ['Mount Field National Park'],
}

export const VALID_SPOT_PARENT_KEYS = new Set(Object.keys(SPOT_PARENT_TOWN_MAP))

export const TOWN_BY_EN_TITLE_ALIAS = {
  Franklin: 'Huonville',
}

export const TOWN_BY_TEXT = [
  { pattern: /朗塞斯顿|launceston/i, town: 'Launceston' },
  { pattern: /霍巴特|hobart/i, town: 'Hobart' },
  { pattern: /德文波特|devonport/i, town: 'Devonport' },
  { pattern: /朗塞斯顿及北部|北部塔马/i, town: 'Launceston' },
  { pattern: /比奇诺|bicheno/i, town: 'Bicheno' },
  { pattern: /圣海伦|st helens/i, town: 'St Helens' },
  { pattern: /斯旺西|swansea/i, town: 'Swansea' },
  { pattern: /德洛兰|deloraine/i, town: 'Deloraine' },
  { pattern: /谢菲尔德|sheffield/i, town: 'Sheffield' },
  { pattern: /斯坦利|stanley/i, town: 'Stanley' },
  { pattern: /伯尼|burnie/i, town: 'Burnie' },
  { pattern: /ulverstone/i, town: 'Ulverstone' },
  { pattern: /企鹅|penguin/i, town: 'Penguin' },
  { pattern: /奥特兰|oatlands/i, town: 'Oatlands' },
  { pattern: /坎贝尔|campbell town/i, town: 'Campbell Town' },
  { pattern: /乔治镇|george town/i, town: 'George Town' },
  { pattern: /低头|low head/i, town: 'George Town' },
  { pattern: /菲尔德山|mount field/i, town: 'Hobart' },
  { pattern: /胡恩谷|huon valley|huonville/i, town: 'Huonville' },
  { pattern: /东海岸|菲欣拿|freycinet/i, town: 'Coles Bay' },
  { pattern: /西北部|cradle|摇篮/i, town: 'Cradle Mountain' },
  { pattern: /西海岸|strahan|斯特拉恩/i, town: 'Strahan' },
  { pattern: /金岛|king island/i, town: 'Currie' },
  { pattern: /弗林德斯|flinders island/i, town: 'Flinders Island' },
]

export const MAIN_DESTINATION_EN_TITLES = new Set([
  'Bruny Island',
  'Tasman Peninsula',
  'Turrakana/Tasman Peninsula',
  'Maria Island',
  'Cradle Mountain',
  'Cradle Mountain-Lake St Clair National Park',
  'Coles Bay',
  'Freycinet National Park',
  'Mount Field National Park',
  'Port Arthur',
  'Strahan',
  'Hobart',
  'Launceston',
  'Richmond',
  'Ross',
  'Flinders Island',
  'King Island',
  'Huonville',
  'Huon Valley',
  'Queenstown',
  'Triabunna',
  'Swansea',
  'Bicheno',
  'St Helens',
  'Devonport',
  'Burnie',
  'Stanley',
  'Zeehan',
  'Oatlands',
  'Campbell Town',
  'George Town',
  'Deloraine',
  'Sheffield',
  'Penguin',
  'Latrobe',
  'Bothwell',
  'Geeveston',
  'Cygnet',
  'Kingston',
  'New Norfolk',
  'Battery Point',
  'Sandy Bay',
  'Mole Creek',
])

export const MAIN_DESTINATION_TITLES = new Set([
  '布鲁尼岛',
  '塔斯曼半岛',
  '玛丽亚岛',
  '摇篮山',
  '圣克莱尔湖国家公园',
  '科尔斯湾',
  '菲欣纳国家公园',
  '费尔德山国家公园',
  '阿瑟港',
  '斯特拉恩小镇',
  '霍巴特海滨',
  '朗塞斯顿',
  '里奇蒙',
  '罗斯镇',
  '弗林德斯岛',
  '国王岛/金岛',
  '胡恩谷',
  '皇后镇',
  '斯旺西',
  '比切诺镇',
  '圣海伦斯',
  '德文港',
  '斯坦利',
  '泽汉',
  '奥特兰兹',
  '坎贝尔镇',
  '乔治镇',
  '德洛兰恩',
  '谢菲尔德',
  '企鹅镇',
  '巴特里角',
  '桑迪湾',
  '吉夫斯顿',
])
