/** 景点 town / belongsToTown 修正映射（enTitle 优先，title 兜底） */

export const BELONGS_TO_BY_EN_TITLE = {
  'Adventure Bay': 'Bruny Island',
  'Mavista Nature Walk': 'Bruny Island',
  'Two Tree Point': 'Bruny Island',
  'Eaglehawk Neck': 'Tasman Peninsula',
  'Tessellated pavement': 'Tasman Peninsula',
  'Cape Pillar': 'Tasman Peninsula',
  'Cape Hauy': 'Tasman Peninsula',
  'Roaring Beach': 'Tasman Peninsula',
  'Spiky Bridge': 'Tasman Peninsula',
  'Spiky Beach': 'Tasman Peninsula',
  'The Painted Cliff': 'Maria Island',
  'Maria Island National Park': 'Maria Island',
  'Darlington Probation Station': 'Maria Island',
  'Dove Lake': 'Cradle Mountain',
  'Barn Bluff': 'Cradle Mountain',
  'Wineglass Bay': 'Coles Bay',
  'Honeymoon Bay': 'Coles Bay',
  'Great Oyster Bay': 'Coles Bay',
  'Moulting Lagoon': 'Coles Bay',
  'Freycinet National Park': 'Coles Bay',
  'Russell Falls': 'Hobart',
  'Horseshoe Falls': 'Hobart',
  'Hastings Caves': 'Huonville',
  'Tahune AirWalk': 'Huonville',
  'Hartz Mountains': 'Geeveston',
  'Ocean Beach': 'Strahan',
  'Gordon River': 'Strahan',
  'Macquarie Harbour': 'Strahan',
  'Southwest National Park': 'Strahan',
  'Franklin-Gordon Wild Rivers National Park': 'Strahan',
  'West Coast Wilderness Railway': 'Strahan',
  'Iron Blow Lookout': 'Queenstown',
  'Ross Bridge': 'Ross',
  'Richmond Bridge': 'Richmond',
  'Richmond Gaol': 'Richmond',
  'Salamanca Market': 'Hobart',
  'Salamanca Arts Centre': 'Hobart',
  'MONA': 'Hobart',
  'Mount Wellington': 'Hobart',
  'Royal Tasmanian Botanical Gardens': 'Hobart',
  'Constitution Dock': 'Hobart',
  'Hobart Waterfront': 'Hobart',
  'The Queens Domain': 'Hobart',
  'Maritime Museum Tasmania': 'Hobart',
  'Tasmanian Museum and Art Gallery': 'Hobart',
  'Mount Nelson': 'Hobart',
  'Battery Point': 'Battery Point',
  'Sandy Bay': 'Sandy Bay',
  'Launceston Gorge': 'Launceston',
  'Bridestowe Lavender Estate': 'Launceston',
  'Ben Lomond': 'Launceston',
  'Tamar Island Wetlands Centre': 'Launceston',
  'Mole Creek Karst National Park': 'Mole Creek',
  'King Solomons Cave': 'Mole Creek',
  'Marakoopa Cave': 'Mole Creek',
  'Mole Creek Caves': 'Mole Creek',
  'Table Cape Lighthouse': 'Wynyard',
  'Table Cape': 'Wynyard',
  'The Table Cape Tulip Farm': 'Wynyard',
  'Fossil Bluff Conservation Area': 'Wynyard',
  'Low Head Pilot Station': 'George Town',
  'Low Head Foghorn': 'George Town',
  'Marine Education Centre - Low Head Lighthouse Precinct': 'George Town',
  'Bass and Flinders Centre/Bass and Flinders Maritime Museum': 'George Town',
  'Strzelecki National Park': 'Flinders Island',
  'Strzelecki Peaks': 'Flinders Island',
  'Deal Island': 'Flinders Island',
  'Killiecrankie': 'Flinders Island',
  'Walls of Jerusalem National Park': 'Mole Creek',
  'Devils Gullet State Reserve': 'Mole Creek',
  'Philosopher Falls': 'Strahan',
  'Granville Harbour': 'Zeehan',
  'Trial Harbour': 'Trial Harbour',
}

export const BELONGS_TO_BY_TITLE = {
  '冒险湾': 'Bruny Island',
  '马维斯塔自然步道': 'Bruny Island',
  '两棵树角步道': 'Bruny Island',
  '鹰颈峡': 'Tasman Peninsula',
  '棋盘道': 'Tasman Peninsula',
  '皮勒角': 'Tasman Peninsula',
  '豪伊角': 'Tasman Peninsula',
  '咆哮海滩': 'Tasman Peninsula',
  'Spiky Bridge': 'Tasman Peninsula',
  'Spiky Beach': 'Tasman Peninsula',
  '彩绘崖': 'Maria Island',
  '酒杯湾': 'Coles Bay',
  '蜜月湾': 'Coles Bay',
  '大牡蛎湾': 'Coles Bay',
  '莫尔廷泻湖': 'Coles Bay',
  '菲欣纳国家公园': 'Coles Bay',
  '鸽子湖': 'Cradle Mountain',
  '谷仓崖': 'Cradle Mountain',
  '罗素瀑布': 'Hobart',
  '马蹄瀑布': 'Hobart',
  '黑斯廷斯洞穴': 'Huonville',
  '海洋海滩': 'Strahan',
  '戈登河': 'Strahan',
  '麦夸里港': 'Strahan',
  '西南国家公园': 'Strahan',
  '富兰克林戈登野河国家公园': 'Strahan',
  '西海岸荒野铁路': 'Strahan',
  '罗斯桥': 'Ross',
  '里奇蒙古桥': 'Richmond',
}

/** 文本关键词 → belongsToTown（当 enTitle/title 未命中时使用） */
export const BELONGS_TO_BY_TEXT = [
  { pattern: /bruny|布鲁尼/i, town: 'Bruny Island', excludeEn: /^Bruny Island$/i },
  { pattern: /maria island|玛丽亚岛/i, town: 'Maria Island', excludeEn: /^Maria Island$/i },
  { pattern: /tasman peninsula|塔斯曼半岛|eaglehawk|鹰颈|port arthur|阿瑟港/i, town: 'Tasman Peninsula', excludeEn: /^(Port Arthur|Turrakana\/Tasman Peninsula|Tasman Peninsula)$/i },
  { pattern: /freycinet|菲欣纳|wineglass|酒杯湾|coles bay|科尔斯湾/i, town: 'Coles Bay', excludeEn: /^(Freycinet National Park|Coles Bay|Wineglass Bay)$/i },
  { pattern: /cradle mountain|摇篮山|dove lake|鸽子湖|lake st clair|圣克莱尔湖/i, town: 'Cradle Mountain', excludeEn: /^(Cradle Mountain|Cradle Mountain-Lake St Clair National Park)$/i },
  { pattern: /strahan|斯特拉恩|macquarie harbour|麦夸里港|gordon river|戈登河/i, town: 'Strahan', excludeEn: /^Strahan$/i },
  { pattern: /flinders island|弗林德斯岛|killiecrankie|strzelecki/i, town: 'Flinders Island', excludeEn: /^Flinders Island$/i },
  { pattern: /king island|金岛|currie/i, town: 'Currie', excludeEn: /^(King Island|Currie)$/i },
]

/** 主目的地 enTitle：这些条目本身不应设置 belongsToTown */
export const MAIN_DESTINATION_EN_TITLES = new Set([
  'Bruny Island',
  'Tasman Peninsula',
  'Turrakana/Tasman Peninsula',
  'Maria Island',
  'Cradle Mountain',
  'Cradle Mountain-Lake St Clair National Park',
  'Coles Bay',
  'Freycinet National Park',
  'Port Arthur',
  'Strahan',
  'Hobart',
  'Launceston',
  'Richmond',
  'Ross',
  'Flinders Island',
  'King Island',
  'Huonville',
  'Huon Valley',
  'Queenstown',
  'Triabunna',
])
